/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'fetchVideos': EventHandler<never, { topic: 'yt.videos.fetched'; data: never } | { topic: 'yt.videos.error'; data: never }>
    'SendTitles': EventHandler<never, never>
    'generateTitles': EventHandler<never, { topic: 'yt.titles.ready'; data: never } | { topic: 'yt.titles.error'; data: never }>
    'ResolveChannel': EventHandler<never, { topic: 'yt.channel.resolved'; data: never } | { topic: 'yt.channel.error'; data: never }>
    'YTSubmitApi': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'YTSubmit'; data: never }>
    'contentHealthMonitor': CronHandler<{ topic: 'content.video.scan'; data: never }>
    'analyseVideos': EventHandler<never, never>
    'scanVideos': EventHandler<never, { topic: 'content.video.resolved'; data: never }>
  }
    
}